### ISSUE TITLE
Update the usage of puppet-redirect

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/UserAdmin#12]
Switch to be using the new path `/sys/puppet-redirect/puppet-redirect.html`.

Please release a new version when done.

**Comment by jwillmer** [comment]
The launcher uses ```"/sys/juicy-redirect/juicy-redirect.html"``` is there a difference and could you make one redirect out of it?

**Comment by warpech** [comment]
@jwillmer good catch! Your question is being answered in https://github.com/StarcounterPrefabs/Launcher/issues/216.

**Comment by warpech** [comment]
Regarding the original matter of this issue, update the path after Starcounter 2.2 stable is released, because previous stable (2.1.177) uses a different path.

**Comment by warpech** [comment]
Looking good, thanks.

**Comment by warpech** [comment]
Sorry to reopen, but you only updated one file. The old path is still present in other HTML template files.

**Comment by aloscha** [comment]
Sorry @warpech, I oversight it. Fix on master

**Comment by warpech** [comment]
Thanks!
