### ISSUE TITLE
Remove the dependency on PropertyMetadata

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/UserAdmin#14]
Remove the dependency on https://github.com/Smorgasbord-Development/PropertyMetadata.

UserAdmin is a prefab app that needs to be self dependent and fully understandable. PropertyMetadata is adding confusion and complication to the building steps.

It is fine to use library like PropertyMetadata for organisation's own apps, but not for Starcounter Samples/prefabs.

**Comment by per-samuelsson** [comment]
+1

**Comment by per-samuelsson** [comment]
Just noticed @jwillmer reported this in #11 too.

**Comment by per-samuelsson** [comment]
Superbump. We really need to fix this. We have complains our users can't build this app.

**Comment by jwillmer** [comment]
:coffee:

**Comment by per-samuelsson** [comment]
Until this is fixed, a **workaround** is to build the public [PropertyMetadata](https://github.com/Smorgasbord-Development/PropertyMetadata) project explicitly, then adjusting the reference to it. This does not invalidate the fact we should consider this a bug IMO, but might be good to know if someone need to proceed urgently.

Thanks @jwillmer for helping out verifying this.

**Comment by per-samuelsson** [comment]
Bumpelybump, we are struggling with this again.

**Comment by andwah** [comment]
I Remove a third party project from the solution and added a precompiled library (dll) into the project. So no more "external" references.

**Comment by per-samuelsson** [comment]
> I Remove a third party project from the solution and added a precompiled library (dll) into the project. So no more "external" references.

Hero! Thanks. I volonteer to test it and close this issue if it works.

**Comment by per-samuelsson** [comment]
> I volonteer to test it and close this issue if it works.

Works like a charm. Thanks @andwah!

**Comment by warpech** [comment]
My issue was really about merging the PropertyMetadata into the project as code, not only as DLL. @andwah don't you think thats viable?

**Comment by per-samuelsson** [comment]
> My issue was really about merging the PropertyMetadata into the project as code, not only as DLL.

Yeah, putting binaries in our repos is never a good practice, and we shouldn't do this long-term. I just thought this issue was about it didn't compile, and now it does.

References should always be kept as versioned dependencies as the first option, and as submodules as the second (but rarely that either). Putting binaries in our repos should always be considered a "hack"/"workaround" that adds to the backlog and have to be fixed eventually.

**Comment by andwah** [comment]
Is there a good solution on how an app should be designed if it uses external libraries?, I mean custom libraries that can not be resolved with Nuget etc..

**Comment by jwillmer** [comment]
> Is there a good solution on how an app should be designed if it uses external libraries?, I mean custom libraries that can not be resolved with Nuget etc..

Upload the lib version to Nuget?

**Comment by andwah** [comment]
> My issue was really about merging the PropertyMetadata into the project as code, not only as DLL

@warpech Well. are you thinking about copying/syninc the code around between repos/projects? i dont think that is a good longterm solution.

**Comment by per-samuelsson** [comment]
> Is there a good solution on how an app should be designed if it uses external libraries?, I mean custom libraries that can not be resolved with Nuget etc..

No. Simply because that's bad design. Dependency management should more or less *always* use the standard pattern with a package manager responsible for resolving external packages.

Basically, to have project that can not adhere to versioning builds of itself and put them on some package repository disqualify that project from being used as an external reference of some other project. It's more or less as simple as that.

**Comment by andwah** [comment]
@jwillmer I agree that is a good solution.. 

But what about the developers that do not want to publish the library on nuget.

**Comment by per-samuelsson** [comment]
> But what about the developers that do not want to publish the library on nuget.

Answered by this:

> Basically, to have project that can not adhere to versioning builds of itself and put them on some package repository disqualify that project from being used as an external reference of some other project. It's more or less as simple as that.

**Comment by andwah** [comment]
I removed the third party binary and replaced it with NuGet handling. 
Fix 525d3a749cd3840c22fd73ff814d0802e8446423

**Comment by warpech** [comment]
173 downloads already, wow! :)

**Comment by andwah** [comment]
well , that was from the first version that was posted as en experiment from over a year ago :-)
