### ISSUE TITLE
Reset password is disabled on every account

### ISSUE THREAD

**Issue by jwillmer** [StarcounterSamples/UserAdmin#25]
I can not reset the password for any user if i'm logged in with the admin account.

**Comment by miyconst** [comment]
@diliger take a look.

**Comment by miyconst** [comment]
There should be an option to select single or double hashing algorithm.

**Comment by jwillmer** [comment]
Should it also be possible to reset his own password? This way I don't need to install another app (and setup another admin account) to change the password of the default admin user.

**Comment by miyconst** [comment]
SignIn 4.x includes basic user profile page with password section.

**Comment by diliger** [comment]
Implemented in this way:
![image](https://cloud.githubusercontent.com/assets/15857369/15401816/e59264a6-1df9-11e6-975d-a6e67732603b.png)

Pushed a pull request. cc @miyconst

**Comment by diliger** [comment]
Published two versions of **UserAdmin** application.

Version `3.0.0` - for SignIn application version `3.x`
Implemented password reset with single password hash.

Version `4.0.0` - for SignIn application version `4.x`
Implemented password reset with double password hash.

Create new user fixed as well.
Removed duplicate code from `Helper.cs`, used functions from `Simplified.SystemUser` class.

**Comment by miyconst** [comment]
@jwillmer please take a look at close the issue if you are satisfied.

**Comment by jwillmer** [comment]
Maybe it would be a good idea to ask the user to check-in again after changing his own password.

**Comment by miyconst** [comment]
>MAybe auto logout the user whos password has been changed - don't know if you can get in trouble with your current session?

Why there should be any problems? The authentication is saved in cookies and it does not matter if you change the password.

**Comment by jwillmer** [comment]
O.K. I only know that some web applications do that. Maybe a security feature? Log out of all browsers on pw reset.

**Comment by jwillmer** [comment]
Have tested version 3.0 - works like intended. Closing issue.

**Comment by miyconst** [comment]
@jwillmer good suggestion, I have moved it to another issue: https://github.com/StarcounterSamples/UserAdmin/issues/27.
