### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/UserAdmin#8]
Now that UserAdmin was upgraded to Polymer 1.1, please release a new version to the app store.
Now including a git tag! https://github.com/StarcounterSamples/AppStoreServer/wiki/How-to-publish-apps

**Comment by andwah** [comment]
The version is already on the appstore  (version 2.0.1-pre7) but i did not follow allt the steps on  https://github.com/StarcounterSamples/AppStoreServer/wiki/How-to-publish-apps.

**Comment by warpech** [comment]
Can you do so? We follow it for all other apps. It greatly improves team workflow.

**Comment by andwah** [comment]
Done.

**Comment by warpech** [comment]
It seems that the git tag was not pushed. 

Thanks!
