### ISSUE TITLE
Starcounter.Node.exe not found

### ISSUE THREAD

**Issue by Prav962** [StarcounterSamples/UserAdmin#9]
Hi I heard about startcounter and try to understand the same. I have downloaded the framework version 2.1.298 (Oct 28, 2015 9:18:11 PM). and trying to run your sample app "UserAdmin" from github. I tried to run but it fails due to this error
Probing location 'C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\Starcounter.Node.exe' because this directory is in the search path.
Could you guys help me to run this sample.
Thanks

**Comment by dan31** [comment]
Hi @Prav962! Thanks for your question. @alemoi will come back to you soon to help you solve the case.

**Comment by alemoi** [comment]
Hi again! I guess the problem lies in outdated version of "UserAdmin" application that uses an outdated Starcounter.Node.dll. Can you please give us a link from where you downloaded/cloned UserAdmin app? Thank you!

**Comment by miyconst** [comment]
I just have checked [UserAdmin](https://github.com/StarcounterSamples/UserAdmin) app with the latest Starcounter (`Starcounter-DevelopNightlyBuilds-2.1.388 (Nov 9, 2015 2:01:00 AM)`) and the application starts.

Could you please update Starcounter and source code to the latest version and try again?

Also, [UserAdmin](https://github.com/StarcounterSamples/UserAdmin) is kind of "advanced" sample, it would be better if you start with something simpler, such as [Barcodes](https://github.com/StarcounterSamples/Barcodes), [Images](https://github.com/StarcounterSamples/Images), [Products](https://github.com/StarcounterSamples/Products), [Launcher](https://github.com/StarcounterSamples/Launcher). All of those apps could work together.

**Note:** you won't be able to test [UserAdmin](https://github.com/StarcounterSamples/UserAdmin) app without [Launcher](https://github.com/StarcounterSamples/Launcher) and [SignIn](https://github.com/StarcounterSamples/SignIn) apps.
